import { Unbounded, Sora } from "next/font/google";
import "./globals.css";
import "@fortawesome/fontawesome-svg-core/style.css";
import { config } from "@fortawesome/fontawesome-svg-core";
config.autoAddcss = false;

import 'remixicon/fonts/remixicon.css'


const Unbounded = Unbounded({
  variable: "--font-unbounded",
  subsets: ["latin"],
  weigth: ["400", "500", "600", "700"]
});

const Sora = Sora({
  variable: "--font-sora",
  subsets: ["latin"],
  weigth: ["400", "500", "600", "700"]
});

export const metadata = {
  title: "Trip-Planner Tours & Travel Webside - K2infocom",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body
        className={`${sore.variable} ${unbounded.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
