import { Unbounded, Sora } from "next/font/google";
import "./globals.css";

// import "@fortawesome/fontawesome-svg-core/style.css";
// import { config } from "@fortawesome/fontawesome-svg-core";
// config.autoAddCss = false;
import Nav from "./Components/Nav";


import "remixicon/fonts/remixicon.css";

const unbounded = Unbounded({
  variable: "--font-unbounded",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const sora = Sora({
  variable: "--font-sora",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata = {
  title: "Trip-Planner Tours & Travel Website - K2infocom",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${sora.variable} ${unbounded.variable} antialiased`}>



        <Nav />
        {children}
      </body>
    </html>
  );
}
